-- MySQL Script generated by MySQL Workbench
-- Mon May 24 14:33:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_rede_social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_rede_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_rede_social` DEFAULT CHARACTER SET utf8 ;
USE `db_rede_social` ;

-- -----------------------------------------------------
-- Table `db_rede_social`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rede_social`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(70) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rede_social`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rede_social`.`tb_postagens` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo_postagem` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `localizacao` VARCHAR(255) NULL,
  `url_anexo` VARCHAR(255) NULL,
  `fk_tb_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagens_tb_usuarios1_idx` (`fk_tb_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuarios1`
    FOREIGN KEY (`fk_tb_usuarios`)
    REFERENCES `db_rede_social`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_rede_social`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_rede_social`.`tb_grupos` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(45) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `qnt_usuarios` INT NOT NULL DEFAULT 500,
  `fk_tb_usuarios` INT NOT NULL,
  `fk_tb_postagens` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `fk_tb_grupos_tb_usuarios1_idx` (`fk_tb_usuarios` ASC) VISIBLE,
  INDEX `fk_tb_grupos_tb_postagens1_idx` (`fk_tb_postagens` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_tb_usuarios1`
    FOREIGN KEY (`fk_tb_usuarios`)
    REFERENCES `db_rede_social`.`tb_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_grupos_tb_postagens1`
    FOREIGN KEY (`fk_tb_postagens`)
    REFERENCES `db_rede_social`.`tb_postagens` (`id_postagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
